name: Aggregate open issues to a single JSON file.
description: Allows the issues to be searched as you type with Instant Issues.
author: Gittenburg <gittenburg@fsinf.at>
runs:
  using: docker
  image: Dockerfile
